### ISSUE TITLE
Allow to provide a list of ignored words

### ISSUE THREAD

**Issue by rixx** [btford/write-good#104]
For example, write-good doesn't know that "read-only" is a term, and tells me that "only" can weaken meaning. So if I'd be able to pass a "--ignore='read-only'", I'd be much more likely to run write-good on my API docs.

**Comment by RichardLitt** [comment]
Sounds like a good addition. I'd welcome a PR for this.

**Comment by blueyed** [comment]
Shouldn't "X-only" be whitelisted by default (at least "read-only" and "write-only")?

**Comment by RichardLitt** [comment]
@blueyed 	Most likely, yes.
