### ISSUE TITLE
Incorrect word parsing

### ISSUE THREAD

**Issue by D1LL1G4F** [btford/write-good#112]
I believe that words with hyphen are parsed incorrectly.![image](https://user-images.githubusercontent.com/26377907/52212234-53532080-288c-11e9-9533-7dee41aecdbc.png)

**Comment by RichardLitt** [comment]
I think you're right. This should be fixed.

**Comment by HonzaMac** [comment]
Problem is in package [too-wordy](https://github.com/duereg/too-wordy) as it uses for finding words regex matching with `\b(blacklisted-words)\b`, when \b does not contain `-` hyphen. That implies, that words with hyphen are parsed wrong.
I see only on possible way right know what to try: 
Change regular expression to include hyphen in words (and possibly also `'` apostrophe) - but then it's becoming specific for english words or similar languages.

If there is anyone who can think of something better.

**Comment by RichardLitt** [comment]
Thanks, @HonzaMac.

- Do other languages not use hyphens? 
- Is cross-language compatibility more important than fixing it in at least one language? (I'd say no.)

**Comment by HonzaMac** [comment]
Detection of boundaries were fixed in package _too-wordy_.
Can we update package here and release new version?

**Comment by RichardLitt** [comment]
Done. Think this can be closed?

**Comment by HonzaMac** [comment]
@RichardLitt I've added test for validation of this change for future proof check.

**Comment by HonzaMac** [comment]
Thank you 🎉
