### ISSUE TITLE
Is this the same as Proselint ?

### ISSUE THREAD

**Issue by DonaldTsang** [btford/write-good#118]
Just wondering if the features do match, since they are both "prose linter".
https://github.com/amperser/proselint

**Comment by RichardLitt** [comment]
It looks similar to me. They weren't developed in conjunction. It does seem that prsoselint has a more extensive ecosystem, which is pretty cool!

**Comment by DonaldTsang** [comment]
@RichardLitt since ProseLint has not been developed in a year, is it possible to integrate some of the features or standards into write-good?

**Comment by RichardLitt** [comment]
I don't see why not. I don't have the time, at the moment, though, but I am happy to look at PRs!
