### ISSUE TITLE
No tags since v0.10.0

### ISSUE THREAD

**Issue by tykeal** [btford/write-good#122]
There have been no tags of versions since version v0.10.0.  We're attempting to use write-good via pre-commit and when referenced via version number (v1.0.3) it fails since there is no version tag or branch for it to checkout and use.

**Comment by RichardLitt** [comment]
Hmm. I can probably fix that. I'm sorry; do you mean git tags, or npm tags?

**Comment by tykeal** [comment]
Git tags. pre-commit checkouts out a git coordinate and the preference is to use version tags.

**Comment by RichardLitt** [comment]
I'm not sure how to automatically update these each time, but I've pushed all of the tags up.

**Comment by tykeal** [comment]
How are the tags getting created? Is it via CI of some sort?

**Comment by RichardLitt** [comment]
Through using npm. They just weren't pushed to master.
