### ISSUE TITLE
mutiple

### ISSUE THREAD

**Issue by Mister-Hope** [btford/write-good#124]
Same as the word only, mutiple can have meanings.

I am not sure mutiple is wordy or unneeded. What should I use if I just want to highlight againest single?

Here is a few examples:

- Footnote can have **markup** and **multiple** paragraphs.
- Allows for multiple flows.
- Highest authority password, you can set multiple passwords by using array
- `tags` accepts `string | string []`, which means that an article can contain multiple tags.

I don't think I am not writing good.

**Comment by RichardLitt** [comment]
It's just a hint. It's not a hard-and-fast this word is wrong.

**Comment by btford** [comment]
The reason "multiple" is called out is that it can in some cases be
replaced with a more precise quantifier: "more than one," "between one and
ten," etc. Same as the rationale for "many."

I think you're right that if you're contrasting between one and many, this
usage is fine. Like Richard said, this is just a tool for helping you think
about what you're writing, not a set of definitive rules.
