### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ChrisChinchilla** [btford/write-good#139]
Is this still maintained @btford ? I ask as I also work a lot on Vale, which includes the Write Good rules anyway and maybe we push all the many people who still seem to drop by this repo over there instead?

**Comment by RichardLitt** [comment]
Hey @ChrisChinchilla! 👋 Yes, this is still maintained, but kind of on a PR-only really.

I'm not sure I understand your question. Is sending people here not working?

**Comment by ChrisChinchilla** [comment]
@RichardLitt Hey! Didn't realise you were here. I meant that as Vale also has to Write good rules and is very actively maintained and much more flexible, would it be a good idea to recommend it to people instead?

**Comment by RichardLitt** [comment]
I think you're free to recommend anything to anyone, so I'm not quite sure what you're asking. Do you think we should shut this down? It works, at the moment, and having a diversity of modules is likely healthy.

**Comment by ChrisChinchilla** [comment]
@RichardLitt Not at all 😅. I'm just saying that if this a project that a lot of people come to look at and it's not really active anymore, and there's another project with comparable functionality (and more) that's very active and widely used, maybe it's constructive to tell newcomers about it?

**Comment by RichardLitt** [comment]
We have a section for recommendations. PRs accepted. 

It is active, it's just not actively having a lot of PRs at the moment. Either @btford or I respond to most pressing issues. Sending newcomers to a different repo would effectively stifle the community, and is similar to shutting it down, to my mind.
