### ISSUE TITLE
ale html file showing </div> repeated.

### ISSUE THREAD

**Issue by cxwx** [btford/write-good#140]
<img width="364" alt="截屏2024-05-08 00 06 37" src="https://github.com/btford/write-good/assets/6235641/fe8b104c-5f4c-4b44-8786-aca1969f4958">

I'm not sure why it is showing
How can I ignore it when editing html?

**Comment by RichardLitt** [comment]
Looks like an issue with your plugin, not with this service. Good luck.

**Comment by cxwx** [comment]
@RichardLitt  so how can I ingore it using some configure?
below is command line result.
<img width="429" alt="截屏2024-05-11 09 14 47" src="https://github.com/btford/write-good/assets/6235641/941753ae-c427-4709-9b69-c6748faeff75">

**Comment by RichardLitt** [comment]
You need to make separate files that only have text, or you need to pipe English text into write-good somehow. This plugin is not made for .html files.
