### ISSUE TITLE
Command line should error on invalid arguments

### ISSUE THREAD

**Issue by benbalter** [btford/write-good#48]
If I pass an invalid test to the command line interface, it should error out and let me know I passed an invalid test.

In my particular case, I wrote a script which passed the `--pasive` argument and ran it on a bunch of content, none the wiser.

If the test I ask for doesn't exist, let me know, rather than leading me to believe I wrote good.

**Comment by btford** [comment]
:+1:

**Comment by TimKam** [comment]
Using something like [commander](https://github.com/tj/commander.js/) for the command line interface would solve this. Would you accept a PR for this?

**Comment by RichardLitt** [comment]
I use meow and minimist for this purpose, too. But any should work. A PR would be great, @TimKam!

**Comment by TimKam** [comment]
I think this can be closed. There is still one edge case: write-good doesn't catch the JS exception when using "too broad" globs, for example when trying ``write-good folder/**/*``. Note that this is **not** a regression. I suggest I create a follow-up ticket for this and fix it.

**Comment by RichardLitt** [comment]
Sounds good to me! Thanks @TimKam!
