### ISSUE TITLE
虞美人

### ISSUE THREAD

**Issue by LazyBois** [btford/write-good#50]
少年听雨歌楼上。红烛昏罗帐。壮年听雨客舟中。江阔云低、断雁叫西风。 
而今听雨僧庐下。鬓已星星也。悲欢离合总无情。一任阶前、点滴到天明。

**Comment by RichardLitt** [comment]
> Teenager listening to the rain song upstairs. Candle faint Luozhang. Prime Machines passenger boat. Jiang wide low cloud, geese called off west.
> Now listen to the rain under Monk Lu. Temples have been the stars. Joys and sorrows always ruthless. By the previous step, bit by bit until dawn.

Thank you.

**Comment by LazyBois** [comment]
I still can't quite believe someone would reply in the first time I used it.luozhang is the curtains around the bed.Thank for your excellent answer.

**Comment by RichardLitt** [comment]
@LazyBois Well, it was an open issue. 

However, while this was cool as a one off, let's keep issues in this repository relevant to write-good.
