### ISSUE TITLE
Vanilla Javascript version?

### ISSUE THREAD

**Issue by koosvanderkolk** [btford/write-good#53]
Please forgive me my ignorance, but how do I get this nice lib to work in my (vanilla) Javacript a.k.a. the web browser?

**Comment by RichardLitt** [comment]
You'll need to use a bundler, such as [browserify](http://browserify.org/), [webpack](https://webpack.github.io/), or [requirejs](http://requirejs.org). Google around for Bundler; this is a bit of a meta task, and isn't relevant to this module in particular.

**Comment by koosvanderkolk** [comment]
Thanks!
