### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by bitboxer** [btford/write-good#57]
Hei,

short question: the last release was in Feb 2015, and I would love to use it in Neomake. For that I would need [this](https://github.com/btford/write-good/commit/a4e52ae33cff729e78e8f502a4ce37e7f7aa9887#commitcomment-19895355) released. Do you have a schedule for the next release?

Thanks!

**Comment by btford** [comment]
Just cut v0.10.0

**Comment by bitboxer** [comment]
Awesome. Thank you so much!
