### ISSUE TITLE
Exclude Monthly & Similar Descriptors

### ISSUE THREAD

**Issue by mbuttler** [btford/write-good#58]
"Monthly" is commonly used as an adjective and noun. It might be nice to have them allowed without needing to resort to turning off the adverb rule.

**Comment by RichardLitt** [comment]
👍 Agreed. Might be a good idea to PR this module: https://github.com/duereg/adverb-where. write-good doesn't actually handle that, at the moment. Reopen this if a PR isn't discussed or merged in a timely fashion.

**Comment by zvyn** [comment]
Just a heads-up that this still is an issue, also for _weekly_. I have to turn this off when time-sheeting because of all the "weekly" meetings. See also: duereg/adverb-where#4.

**Comment by RichardLitt** [comment]
Opened duereg/adverb-where#5.
