### ISSUE TITLE
Support languages other than English

### ISSUE THREAD

**Issue by TimKam** [btford/write-good#64]
I forked `write-good` to add a `--lang` option (with English being the default option) and to implement some basic features for German language linting.
Would you consider incorporating such changes, given they are fully backwards compatible?
Or do you prefer to keep this linter English-only?

**Comment by RichardLitt** [comment]
I would like this; what do you think, @btford? 

We could also link to `schreibe-gut` or something similar.

**Comment by TimKam** [comment]
An alternative to an independent fork is a plugin system: enabling `write-good` to read a configuration file that references modules for additional languages. This simplifies supporting multiple languages in other projects ( i.e. editor plugins), while keeping the maintenance effort in this project low.

**Comment by btford** [comment]
I'm open to accepting this, but I'm a bit worried about scope creep. It's tricky to have this work for all languages, though there may be some common bits. We already attempt to extract individual checks to their own libs, but perhaps that's not enough.

I'll leave it to your discretion @RichardLitt.

**Comment by RichardLitt** [comment]
I've been thinking about it, and I agree about scope creep.

I think languages are unique enough that I am not sure that the rules we've listed here work cross-linguistically. For instance, the `passive` voice is not an issue in many languages - many of which do not actually have a passive voice. (Actually, I don't think the passive voice is an error at all, and I've said that here before. A lot of what people misjudge as the passive is just people using gerunds). Disabling `So` in German wouldn't make sense. German doesn't have the same cadence that English has. Weasel words or `tooWordy` are, I would think, not as much of an issue in French, where the language is naturally more flowery in academic texts than in English (prove me wrong! I would love that). 

I think what would be better is if you would make another module - `schreibe-gut`. I would be happy to link it in the README. (Ich kann auch Deutsch sprechen, ein bischen). What do you think?

**Comment by TimKam** [comment]
Of course, every language needs its own rule types. The approach I like best is writing `schreibe-gut` - working title ;-) - as an extension for `write-good` and to add a feature to `write-good` that lets you reference node modules for further languages in the configuration. Like this, we ensure my module (and possibly modules for other languages) use `write-good`'s interface. This makes it a bit easier to have `good-write` editor plugins support additional languages, I suppose. Anyway, these are just my thoughts, no strong opinion here.

**Comment by RichardLitt** [comment]
That would work for me. Want to make a PR of it? :)

**Comment by TimKam** [comment]
Sure, I need to adjust my implementation and will then create a PR :-)

**Comment by TimKam** [comment]
I think this issue can be closed.

**Comment by RichardLitt** [comment]
@TimKam Made it work appropriately? :D

**Comment by TimKam** [comment]
Custom checks generally work. My `schreib-gut` plugin is a bit limited, though. But on second thought, I think I should add more documentation on how to write custom checks/plugins.

**Comment by RichardLitt** [comment]
> I should add more documentation on how to write custom checks/plugins.

That'd be great to have! If you could do that, we can close this issue. :)

**Comment by RichardLitt** [comment]
Thanks @TimKam!
