### ISSUE TITLE
[suggestion] Optional E-Prime Mode

### ISSUE THREAD

**Issue by Vorror** [btford/write-good#70]
What do you think about [E-Prime](https://en.wikipedia.org/wiki/E-Prime)(Optional and enabled by a flag)?

It would be an interesting new option.

**Comment by RichardLitt** [comment]
As an exercise it might be interesting, but I don't think it is a useful way to prescribe language use. I'm very anti-prescriptivist, though, so @btford might have a different opinion. As an option I don't think it would hurt too much. 

Adding it as a module makes sense to me.

**Comment by Vorror** [comment]
Definitely. It'll allow users to optionally change-up sentence structure so their text doesn't become to repetitive. I consider it more of an informational thing, not a "rule".

**Comment by RichardLitt** [comment]
> It'll allow users to optionally change-up sentence structure so their text doesn't become too repetitive.

This I like. PRs accepted if you can get a nice module up and running with some tests. 👍

**Comment by Vorror** [comment]
Seems easy enough. I'll get on it!

**Comment by RichardLitt** [comment]
Thanks again!
