### ISSUE TITLE
E-prime linting doesn’t support smart quotes

### ISSUE THREAD

**Issue by hilton** [btford/write-good#79]
E-prime linting doesn’t report errors for words including _to be_ that use contractions containing curly/smart/typographer’s quotations marks.

To reproduce:

1. enable E-prime linting (Settings / Additional arguments / `--yes-eprime`)
2. save a document containing the words `isn’t isn't`

Expected: both words trigger the `is a form of 'to be'` linting error/warning.

Observed: `isn’t` doesn’t result in an error.

**Comment by RichardLitt** [comment]
Thanks, @hilton. I'm copying this issue over to the [e-prime repo](https://github.com/Vorror/e-prime) and closing it here.

**Comment by RichardLitt** [comment]
@hilton This should now be fixed.
