### ISSUE TITLE
Chrome extension?

### ISSUE THREAD

**Issue by christianbundy** [btford/write-good#90]
I'm surprised this hasn't been asked before, but has this (or any similar projects) been turned into a Chrome extension that operates on text input? Thanks for your help!

**Comment by RichardLitt** [comment]
Not that I know of. That would be pretty sweet!

**Comment by btford** [comment]
Would also be happy to see someone do this!

This code is MIT licensed for a reason– go nuts folks!

**Comment by danielnaber** [comment]
We (LanguageTool) have a Chrome add-on that you could start with: https://github.com/languagetool-org/languagetool-browser-addon

**Comment by christianbundy** [comment]
@danielnaber Sorry, but I don't want to send all of my text to your server -- especially seeing as how we're on a repo for a JavaScript English linter. Thanks anyway!
