### ISSUE TITLE
Glob no longer working

### ISSUE THREAD

**Issue by jputrino** [btford/write-good#94]
Following the recent commits, our checks that use globs are no longer working. Every attempt to run `write-good *.rst` results in a "not a valid argument" error:

```
putrino: docs (develop)$ write-good --version
0.12.0
putrino: docs (develop)$ write-good *.rst
"index.rst" is not a valid argument.
putrino: docs (develop)$ write-good ./*.rst
"./index.rst" is not a valid argument.
putrino: docs (develop)$ write-good ./index.rst
In ./index.rst
=============
simply *AS3*) is a flexible, low-overhead mechanism for managing
^^^^^^
"simply" can weaken meaning on line 12 at column 0
-------------
Schema, and declarations validate according to JSON Schema. AS3 accepts
                         ^^^^^^^^
"validate" is wordy or unneeded on line 17 at column 30
```

**Comment by RichardLitt** [comment]
@TimKam Looks like we didn't catch this with the tests. Can you help out with this? 

@jputrino Thanks for letting us know! We recently merged a new CLI tool, and it looks like this use case wasn't covered. Sorry about that. Any help in the form of a PR would be great.

**Comment by TimKam** [comment]
I'm so sorry! I added a PR for a quick fix, but did not write tests, yet.

**Comment by RichardLitt** [comment]
@TimKam Let's add some tests first. Thanks for moving so fast!

**Comment by RichardLitt** [comment]
@jputrino This should be good now! Reinstall, let me know, and let's see if we can close this. Thanks, @TimKam.

**Comment by jputrino** [comment]
It works!! @RichardLitt @TimKam Thanks so much, you rock!
