### ISSUE TITLE
Wondering if I can use this with markdown?

### ISSUE THREAD

**Issue by twhite96** [btford/write-good#97]
Was wondering if `write-good` can parse markdown for its suggestions?

I saw someone's web demo and tried it but it didn't seem to recognize:

`**So**`

Just curious.

**Comment by RichardLitt** [comment]
I'm not sure it will work with `**so**`, but it should work fine with `** so **`. Any patches to allow Markdown functionality would be welcome. This could also be extended to, say, html. `<a>So</a>` could also be flagged.

**Comment by twhite96** [comment]
Okay. Thanks. Will see what I can do here.

**Comment by twhite96** [comment]
Just created a PR for this.

**Comment by RichardLitt** [comment]
Awesome, thank you! We'll get to this when we have some time. Thanks.

**Comment by marvindanig** [comment]
Is there an update on accepting the PR for markdown?

**Comment by RichardLitt** [comment]
@marvindanig 	Looks like this is still open. :)

**Comment by matkoniecz** [comment]
It was #98 but in ended closed without merging
