### ISSUE TITLE
Any examples of using this in a React web app as a helper file?

### ISSUE THREAD

**Issue by twhite96** [btford/write-good#99]
There was another issue and comment to that issue using write-good in a React app but I am not looking to make it a component per se. I'm looking to use it as a helper. Any suggestions?

**Comment by btford** [comment]
After installing this, you should be able to import and use it within any existing component:

```
import writeGood from 'write-good';

const MyReactComponent = ({text}) => 
  (<div>{writeGood(text).map(({suggestion}) => suggestion)}</div>);
```

**Comment by twhite96** [comment]
WOW! Thanks @btford. Just what I needed. Going to close this.

**Comment by twhite96** [comment]
I'd like to include this in another component I already made. I have the Simple MDE and I want to add this as a prop to the SMDE editor. I have:

```js
checkText = text => {
    writeGood(text).map(({ suggestion }) => suggestion);
  }

// Some more logic

 <SimpleMDEReact
            className="smde-editor-styles"
            corrections={this.checkText}
            editorStyle={editorStyle}
            label="Markdown Editor"
            onChange={this.handleChange1}
            options={{
              autofocus: true,
              spellChecker: true,
              // etc.
            }}
            value={this.state.textValue1}
          />
        </div>
```

I know this is completely wrong but I am not sure where. I guess I *could* make this a component and import it into the SMDE component. Any suggestions?
